#!/usr/bin/env python3
"""Convert the warroom berserker-gorilla art into an RGB565 C header for the
Marauder v7 TFT (ILI9341, 240x320 portrait). Same image as the warroom PWA
splash, so app and rig share one look.

Output: GorillaSplash.h with a PROGMEM uint16_t[240*320] array + dimensions.
Rendered via TFT_eSPI pushImage() with setSwapBytes(true).
"""
from PIL import Image
import sys

SRC = r"D:\Projekte\warroom\app\static\img\splash-portrait.webp"
DST = r"D:\Projekte\warroom-rig\ESP32Marauder\esp32_marauder\GorillaSplash.h"
W, H = 240, 320

img = Image.open(SRC).convert("RGB")

# cover-fit: scale so the image fills WxH, then center-crop
src_w, src_h = img.size
scale = max(W / src_w, H / src_h)
new_w, new_h = round(src_w * scale), round(src_h * scale)
img = img.resize((new_w, new_h), Image.LANCZOS)
left = (new_w - W) // 2
top = (new_h - H) // 2
img = img.crop((left, top, left + W, top + H))

px = img.load()
vals = []
for y in range(H):
    for x in range(W):
        r, g, b = px[x, y]
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        vals.append(rgb565)

with open(DST, "w") as f:
    f.write("// Auto-generated by tools/make_splash.py -- do not edit by hand.\n")
    f.write("// warroom berserker-gorilla boot splash, RGB565, 240x320 (ILI9341).\n")
    f.write("// Same art as the warroom PWA splash. Draw with TFT_eSPI pushImage\n")
    f.write("// + setSwapBytes(true).\n")
    f.write("#pragma once\n#include <Arduino.h>\n\n")
    f.write(f"#define GORILLA_SPLASH_W {W}\n")
    f.write(f"#define GORILLA_SPLASH_H {H}\n\n")
    f.write("const uint16_t gorilla_splash[GORILLA_SPLASH_W * GORILLA_SPLASH_H] PROGMEM = {\n")
    for i in range(0, len(vals), 12):
        chunk = vals[i:i + 12]
        f.write("  " + ",".join(f"0x{v:04X}" for v in chunk) + ",\n")
    f.write("};\n")

kb = len(vals) * 2 / 1024
print(f"Wrote {DST}")
print(f"{W}x{H} = {len(vals)} px, {kb:.1f} KB flash (PROGMEM)")
