# -*- coding: utf-8 -*-
# Generate GorillaMini.h: 22x22 RGB565 head crop of ape-herald, matted on bronze.
from PIL import Image
import os

SRC = "D:/Projekte/warroom/app/static/img/ape-herald.webp"
OUT = "D:/Projekte/warroom-rig/ESP32Marauder/esp32_marauder/GorillaMini.h"
BRONZE = (90, 73, 33)   # STATUSBAR_COLOR 0x5A44 top-bar background
N = 22

im = Image.open(SRC).convert("RGBA")
w, h = im.size
print("src size", w, h)
# ape-herald is a bust/emblem; take a top-biased centered square so the head fills it
side = int(min(w, h) * 0.92)
cx = w // 2
top = int(h * 0.02)
box = (cx - side // 2, top, cx - side // 2 + side, top + side)
im = im.crop(box).resize((N, N), Image.LANCZOS)

# matte onto bronze
bg = Image.new("RGBA", (N, N), BRONZE + (255,))
im = Image.alpha_composite(bg, im).convert("RGB")

px = list(im.getdata())
vals = []
for (r, g, b) in px:
    vals.append(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3))

with open(OUT, "w") as f:
    f.write("// Auto-generated by tools/make_mini.py -- do not edit by hand.\n")
    f.write("// warroom-rig top-bar mascot, RGB565, 22x22, matted on bronze 0x5A44.\n")
    f.write("// Draw with TFT_eSPI pushImage + setSwapBytes(true).\n")
    f.write("#pragma once\n#include <Arduino.h>\n\n")
    f.write("#define GORILLA_MINI_W 22\n#define GORILLA_MINI_H 22\n\n")
    f.write("const uint16_t gorilla_mini[GORILLA_MINI_W * GORILLA_MINI_H] PROGMEM = {\n")
    for i in range(0, len(vals), 12):
        f.write("  " + ",".join("0x%04X" % v for v in vals[i:i+12]) + ",\n")
    f.write("};\n")
print("wrote", OUT, "bytes:", len(vals) * 2)
